# Generated by Django 3.2.18 on 2023-04-02 18:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='活动介绍')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '优惠活动',
                'verbose_name_plural': '优惠活动',
                'db_table': 'fs_activity',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名/名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '优惠类型',
                'verbose_name_plural': '优惠类型',
                'db_table': 'fs_discount_type',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=255, null=True, upload_to='course/cover', variations={'thumb_1080x608': (1080, 608), 'thumb_108x61': (108, 61, True), 'thumb_540x304': (540, 304)}, verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='详情介绍'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='remark',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='章节介绍'),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='remark',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='方向描述'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='teacher', variations={'thumb_400x400': (400, 400), 'thumb_50x50': (50, 50, True), 'thumb_800x800': (800, 800)}, verbose_name='讲师头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1024, verbose_name='讲师描述'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名/名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('condition', models.IntegerField(blank=True, default=0, help_text='设置享受优惠的价格条件,如果不填或0则没有优惠门槛', verbose_name='满足优惠的价格条件')),
                ('sale', models.TextField(help_text='\n        0表示免费；<br>\n        *号开头表示折扣价，例如填写*0.82,则表示八二折；<br>\n        -号开头表示减免价, 例如填写-100,则表示减免100；<br>', verbose_name='优惠公式')),
                ('discount_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='discount_list', to='course.discounttype', verbose_name='优惠类型')),
            ],
            options={
                'verbose_name': '优惠公式',
                'verbose_name_plural': '优惠公式',
                'db_table': 'fs_discount',
            },
        ),
        migrations.CreateModel(
            name='CourseActivityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名/名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('activity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='course.activity', verbose_name='活动')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='course.course', verbose_name='课程')),
                ('discount', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='course.discount', verbose_name='优惠')),
            ],
            options={
                'verbose_name': '课程参与活动的价格表',
                'verbose_name_plural': '课程参与活动的价格表',
                'db_table': 'fs_course_activity_price',
            },
        ),
    ]
