# Generated by Django 3.2.18 on 2023-04-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20230402_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '实战课程'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
    ]
