# Generated by Django 3.2.18 on 2023-04-04 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_alter_course_course_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名/名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总价')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('order_number', models.CharField(max_length=64, verbose_name='订单号')),
                ('order_status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已取消'), (3, '已超时')], default=0, verbose_name='订单状态')),
                ('pay_type', models.SmallIntegerField(choices=[(0, '支付宝'), (1, '微信'), (2, '余额')], default=1, verbose_name='支付方式')),
                ('order_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='订单描述')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'fs_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名/名称/标题')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('orders', models.SmallIntegerField(default=0, verbose_name='序号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='课程原价')),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='课程实价')),
                ('discount_name', models.CharField(default='', max_length=120, verbose_name='优惠类型')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_orders', to='course.course', verbose_name='课程')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_courses', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'fs_order_course',
            },
        ),
    ]
