# Generated by Django 3.2.18 on 2023-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(0, '支付宝'), (1, '微信'), (2, '余额')], default=0, verbose_name='支付方式'),
        ),
    ]
