# Generated by Django 3.2.18 on 2023-04-02 18:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, default='avatar/2023/avatar.jpg', force_min_size=False, null=True, upload_to='avatar/%Y', variations={'thumb_400x400': (400, 400), 'thumb_50x50': (50, 50, True), 'thumb_800x800': (800, 800)}, verbose_name='个人头像'),
        ),
    ]
